### ISSUE TITLE
Ansible Error when Installer not un-packed 

### ISSUE THREAD

**Issue by jonesbra** [NSO-developer/nso-vagrant#2]
If the installer isn't unpacked after downloading from Cisco (nso-5.1.0.1.linux.x86_64.signed.bin -> nso-5.1.0.1.linux.x86_64.installer.bin) Ansible can't find the appropriate file and throws an error.

[nso-vagrant-error.txt](https://github.com/NSO-developer/nso-vagrant/files/3347143/nso-vagrant-error.txt)

Let's make Ansible detect if the installer has been unpacked and unpack the installer if it is not.

Not a huge issue so will get to this later.

**Comment by jabelk** [comment]
makes sense, feel free to submit a PR, thanks!

For others who have not unpacked it before in the meantime, use `sh nso-5.1.0.1.linux.x86_64.signed.bin` to extract the bin from the signed bin, and put the `nso-5.1.0.1.linux.x86_64.installer.bin` in the `files` not the `*signed.bin`

**Comment by jabelk** [comment]
fixed
